---
title: "eds212-day2-tasks"
author: "Stephen Carroll"
format: html
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse, palmerpenguins)


```

```{r}
# this is a test ----
# create an expression ----
fx <- expression(x^2)

# evaluate at x = 3
x = 3

# find the deriv with respect to x ----
dfdx <- D(expr = fx, name = "x")
dfdx

# Find the slope at x = 3 -----

eval(dfdx)
```

```{r}
# create an expression ----
Pa <- expression(2 * (3 * a + 2)^4 - 5)

# evaluate at a = 1.2----
a = 1.2

# find the deriv with respect to x ----
dPdx <- D(expr = Pa, name = "a")
dPdx

# Find the slope at a = 1.2
eval(dPdx)
```

```{r}
library(palmerpenguins)
data(package = "palmerpenguins")
penguins <- penguins
```

```{r}
ggplot(data = penguins, aes(x = bill_length_mm, y = bill_depth_mm)) +
geom_point()+
  xlab("Bill length mm") +
  ylab("Bill depth mm") +
  ggtitle("Penguin bill length vs. depth")
  

```

```{r}
ggplot(data = penguins, aes(x = species, y = flipper_length_mm)) +
geom_jitter( aes(color = species))+
  xlab("Species") +
  ylab("Flipper length mm") +
  ggtitle("Penguin flipper length by species") +
  facet_wrap (~island) +
  theme_minimal()
```

```{r}
ggplot(data = penguins, aes(x = sex, y = body_mass_g)) +
  geom_line( aes(color = species, lwd = 1))+
  xlab("sex")+
  ylab("body mass grams")+
  ggtitle("body mass of differnet penguin species by sex")+
  facet_wrap(~species)+
  theme_bw()

```

```{r}
penguins_raw <- penguins_raw
```



